# Deletes all previously seeded data
User.destroy_all
Restaurant.destroy_all
FoodItem.destroy_all

# All Restaurant locations [ Dona Bessy & Dona Cecy ]
arlington = Restaurant.create!(location: 'Arlington', phone_number: '703-248-9400', manager: 'Rafael')
springfield = Restaurant.create!(location: 'Springfield', phone_number: '703-333-5074', manager: 'Natelie')
rockville = Restaurant.create!(location: 'Rockville', phone_number: '301-978-7993', manager: 'Christopher')
langley = Restaurant.create!(location: 'Langley Park', phone_number: '301-448-1308', manager: 'TBD')

# Security Levels
# 3 = [tech, owner]     2 = [manager]     1 = [employee]
ar_tech = User.create!(username: 'ar_tech', password: '9400', security_level: 3, restaurant_id: arlington.id)
sp_tech = User.create!(username: 'sp_tech', password: '5074', security_level: 3, restaurant_id: springfield.id)
ro_tech = User.create!(username: 'ro_tech', password: '7993', security_level: 3, restaurant_id: rockville.id)
lp_tech = User.create!(username: 'lp_tech', password: '1308', security_level: 3, restaurant_id: langley.id)

# International
food_item1 = FoodItem.create!(name: 'Yuca Congelada', store: 'International')
food_item2 = FoodItem.create!(name: 'Tamarindo Frizado', store: 'International')
food_item3 = FoodItem.create!(name: 'Hoja de Platano', store: 'International')
food_item4 = FoodItem.create!(name: 'Queso de Barra loty', store: 'International')
food_item5 = FoodItem.create!(name: 'Valde de Crema', store: 'International')
food_item6 = FoodItem.create!(name: 'Horchata loty', store: 'International')
food_item7 = FoodItem.create!(name: 'Marañon', store: 'International')
food_item8 = FoodItem.create!(name: 'Maracuya', store: 'International')
food_item9 = FoodItem.create!(name: 'Mango', store: 'International')
food_item10 = FoodItem.create!(name: 'Nectar narnj y zana', store: 'International')
food_item11 = FoodItem.create!(name: 'Jugo de mango', store: 'International')
food_item12 = FoodItem.create!(name: 'Canela en rajas', store: 'International')
food_item13 = FoodItem.create!(name: 'Tripa de 10 libras', store: 'International')
food_item14 = FoodItem.create!(name: 'Oregano Molido', store: 'International')
food_item15 = FoodItem.create!(name: 'Achote Molido', store: 'International')
food_item16 = FoodItem.create!(name: 'Pimienta Gorda', store: 'International')
food_item17 = FoodItem.create!(name: 'Chile Molido', store: 'International')
food_item18 = FoodItem.create!(name: 'Pimienta Negra molida', store: 'International')
food_item19 = FoodItem.create!(name: 'Ajo Granulado', store: 'International')
food_item20 = FoodItem.create!(name: 'Hoja de Laurel', store: 'International')
food_item21 = FoodItem.create!(name: 'Consome de Pollo knor', store: 'International')
food_item22 = FoodItem.create!(name: 'Consome de Res knorr', store: 'International')
food_item23 = FoodItem.create!(name: 'Comino entero', store: 'International')
food_item24 = FoodItem.create!(name: 'Chile rojo molido', store: 'International')
food_item25 = FoodItem.create!(name: 'Kolashampan', store: 'International')
food_item26 = FoodItem.create!(name: 'Frijol de seda', store: 'International')
food_item27 = FoodItem.create!(name: 'Ajonjolin', store: 'International')
food_item28 = FoodItem.create!(name: 'Queso duro(maqueta)', store: 'International')
food_item29 = FoodItem.create!(name: 'yucateco verde', store: 'International')
food_item30 = FoodItem.create!(name: 'yucateco rojo', store: 'International')
food_item31 = FoodItem.create!(name: 'Masabrosa', store: 'International')
food_item32 = FoodItem.create!(name: 'Dulce de Panela', store: 'International')
food_item33 = FoodItem.create!(name: 'Pastilla de cuajo', store: 'International')
food_item34 = FoodItem.create!(name: 'Tamal de Elote', store: 'International')
food_item35 = FoodItem.create!(name: 'Sea Food mix', store: 'International')
food_item36 = FoodItem.create!(name: 'Maicena', store: 'International')

# Mega Mart
food_item37 = FoodItem.create!(name: 'Robertoni de Camaron', store: 'Mega Mart')
food_item38 = FoodItem.create!(name: 'Alcaparras', store: 'Mega Mart')
food_item39 = FoodItem.create!(name: 'Tilapia', store: 'Mega Mart')
food_item40 = FoodItem.create!(name: 'Pechuga', store: 'Mega Mart')
food_item41 = FoodItem.create!(name: 'Chorizo', store: 'Mega Mart')
food_item42 = FoodItem.create!(name: 'Loroco', store: 'Mega Mart')
food_item43 = FoodItem.create!(name: 'Azafran', store: 'Mega Mart')

# Leonard Paper
food_item44 = FoodItem.create!(name: 'Bolsa de Basura', store: 'Leonard Paper')
food_item45 = FoodItem.create!(name: 'Servilleta Grande', store: 'Leonard Paper')
food_item46 = FoodItem.create!(name: 'Servilleta pequeña', store: 'Leonard Paper')
food_item47 = FoodItem.create!(name: 'Vasos bebida caliente', store: 'Leonard Paper')
food_item48 = FoodItem.create!(name: 'Papel Pupusa', store: 'Leonard Paper')
food_item49 = FoodItem.create!(name: 'Vasos de Sopa grande', store: 'Leonard Paper')
food_item50 = FoodItem.create!(name: 'Tapadera de Sopa', store: 'Leonard Paper')
food_item51 = FoodItem.create!(name: 'Caja pupusa pequena', store: 'Leonard Paper')
food_item52 = FoodItem.create!(name: 'Caja para Carne', store: 'Leonard Paper')
food_item53 = FoodItem.create!(name: 'Caja para platanos', store: 'Leonard Paper')
food_item54 = FoodItem.create!(name: 'Tapadera platano', store: 'Leonard Paper')
food_item55 = FoodItem.create!(name: 'Cajas yucca', store: 'Leonard Paper')
food_item56 = FoodItem.create!(name: 'Tapadera yucca', store: 'Leonard Paper')
food_item57 = FoodItem.create!(name: 'Vasitos miel', store: 'Leonard Paper')
food_item58 = FoodItem.create!(name: 'Tapa miel', store: 'Leonard Paper')
food_item59 = FoodItem.create!(name: 'Cajas pan', store: 'Leonard Paper')
food_item60 = FoodItem.create!(name: 'vasitos salsa pan', store: 'Leonard Paper')
food_item61 = FoodItem.create!(name: 'Tapa salsa pan', store: 'Leonard Paper')
food_item62 = FoodItem.create!(name: 'Vasitos para frijoles', store: 'Leonard Paper')
food_item62 = FoodItem.create!(name: 'Tapa vasitos frijoles', store: 'Leonard Paper')
food_item63 = FoodItem.create!(name: 'Empaque cubierto', store: 'Leonard Paper')
food_item64 = FoodItem.create!(name: 'Cajas para combo', store: 'Leonard Paper')
food_item65 = FoodItem.create!(name: 'Vasos para soda', store: 'Leonard Paper')
food_item66 = FoodItem.create!(name: 'Vasos 16 onz fresco', store: 'Leonard Paper')
food_item67 = FoodItem.create!(name: 'Vasos sopa pequeño', store: 'Leonard Paper')
food_item68 = FoodItem.create!(name: 'Tapadera café', store: 'Leonard Paper')
food_item69 = FoodItem.create!(name: 'Bolsa papel 4', store: 'Leonard Paper')
food_item70 = FoodItem.create!(name: 'Bolsa papel 8', store: 'Leonard Paper')
food_item71 = FoodItem.create!(name: 'Bolsa papel 12', store: 'Leonard Paper')
food_item72 = FoodItem.create!(name: 'Cuchara para ensalad', store: 'Leonard Paper')
food_item73 = FoodItem.create!(name: 'Vasos fresco G  32', store: 'Leonard Paper')
food_item74 = FoodItem.create!(name: 'Tapa fresco G 32', store: 'Leonard Paper')
food_item75 = FoodItem.create!(name: 'Tapa vaso pequeno', store: 'Leonard Paper')
food_item76 = FoodItem.create!(name: 'Papel para el baño', store: 'Leonard Paper')
food_item77 = FoodItem.create!(name: 'Guantes M', store: 'Leonard Paper')
food_item78 = FoodItem.create!(name: 'Guantes S', store: 'Leonard Paper')
food_item79 = FoodItem.create!(name: 'Desinfectante manos', store: 'Leonard Paper')
food_item80 = FoodItem.create!(name: 'Jabon para manos', store: 'Leonard Paper')
food_item81 = FoodItem.create!(name: 'Pajillas', store: 'Leonard Paper')
food_item82 = FoodItem.create!(name: 'Cargador de vaso', store: 'Leonard Paper')
food_item83 = FoodItem.create!(name: 'Liquido para plancha', store: 'Leonard Paper')
food_item84 = FoodItem.create!(name: 'Gabachas', store: 'Leonard Paper')

# Meat Market
food_item85 = FoodItem.create!(name: 'Costilla Churrasco', store: 'Meat Market')
food_item86 = FoodItem.create!(name: 'Costilla para Sopa', store: 'Meat Market')
food_item87 = FoodItem.create!(name: 'Gallina', store: 'Meat Market')
food_item88 = FoodItem.create!(name: 'Pata para Sopa', store: 'Meat Market')

# Osorio
food_item89 = FoodItem.create!(name: 'Carne /Asar', store: 'Osorio')
food_item90 = FoodItem.create!(name: 'Masita', store: 'Osorio')
food_item91 = FoodItem.create!(name: 'Carne /Ch.', store: 'Osorio')
food_item92 = FoodItem.create!(name: 'Pollo', store: 'Osorio')

#Produce
food_item93 = FoodItem.create!(name: 'Vinagre', store: 'Produce')
food_item94 = FoodItem.create!(name: 'Repollo', store: 'Produce')
food_item95 = FoodItem.create!(name: 'Zanahoria', store: 'Produce')
food_item96 = FoodItem.create!(name: 'Cebolla blanca', store: 'Produce')
food_item97 = FoodItem.create!(name: 'Cebolla roja', store: 'Produce')
food_item98 = FoodItem.create!(name: 'Vino tinto', store: 'Produce')
food_item99 = FoodItem.create!(name: 'Platano', store: 'Produce')
food_item100 = FoodItem.create!(name: 'Rabano', store: 'Produce')
food_item101 = FoodItem.create!(name: 'Limon', store: 'Produce')
food_item102 = FoodItem.create!(name: 'Tomate salsa', store: 'Produce')
food_item103 = FoodItem.create!(name: 'Tomate ensal', store: 'Produce')
food_item104 = FoodItem.create!(name: 'Chile verde', store: 'Produce')
food_item105 = FoodItem.create!(name: 'Lechuga', store: 'Produce')
food_item106 = FoodItem.create!(name: 'Ayote', store: 'Produce')
food_item107 = FoodItem.create!(name: 'Pepino', store: 'Produce')
food_item108 = FoodItem.create!(name: 'Cilantro', store: 'Produce')
food_item109 = FoodItem.create!(name: 'Apio', store: 'Produce')
food_item110 = FoodItem.create!(name: 'Yerba buena', store: 'Produce')
food_item111 = FoodItem.create!(name: 'Aguacate', store: 'Produce')
food_item112 = FoodItem.create!(name: 'Huevos', store: 'Produce')
food_item113 = FoodItem.create!(name: 'Jalapeno', store: 'Produce')
food_item114 = FoodItem.create!(name: 'Manzana roja', store: 'Produce')
food_item115 = FoodItem.create!(name: 'Manazana verd', store: 'Produce')
food_item116 = FoodItem.create!(name: 'Uva', store: 'Produce')
food_item117 = FoodItem.create!(name: 'Melon', store: 'Produce')
food_item118 = FoodItem.create!(name: 'Piña', store: 'Produce')
food_item119 = FoodItem.create!(name: 'Güisquil', store: 'Produce')
food_item120 = FoodItem.create!(name: 'Papa', store: 'Produce')
food_item121 = FoodItem.create!(name: 'Elote', store: 'Produce')
food_item122 = FoodItem.create!(name: 'Ejote', store: 'Produce')
food_item123 = FoodItem.create!(name: 'Espinaca', store: 'Produce')
food_item123 = FoodItem.create!(name: 'Gengibre', store: 'Produce')

# Sysco
food_item124 = FoodItem.create!(name: 'Pure de Tomate', store: 'Sysco')
food_item125 = FoodItem.create!(name: 'Tomate Juice', store: 'Sysco')
food_item126 = FoodItem.create!(name: 'Azucar', store: 'Sysco')
food_item127 = FoodItem.create!(name: 'Salt', store: 'Sysco')
food_item128 = FoodItem.create!(name: 'Platano Frizada', store: 'Sysco')
food_item129 = FoodItem.create!(name: 'Margarina', store: 'Sysco')
food_item130 = FoodItem.create!(name: 'Heavy cream', store: 'Sysco')
food_item131 = FoodItem.create!(name: 'Crema para cafe', store: 'Sysco')
food_item132 = FoodItem.create!(name: 'Ajo pelado', store: 'Sysco')
food_item133 = FoodItem.create!(name: 'Ranch', store: 'Sysco')
food_item134 = FoodItem.create!(name: 'Camarones tomate', store: 'Sysco')
food_item135 = FoodItem.create!(name: 'Camarones pupusa', store: 'Sysco')
food_item136 = FoodItem.create!(name: 'Salsa lee & perry', store: 'Sysco')
food_item232 = FoodItem.create!(name: 'Queso Mozarela', store: 'Sysco')
food_item233 = FoodItem.create!(name: 'Conchas Negras', store: 'Sysco')

# Sam's Club
food_item137 = FoodItem.create!(name: 'Chicles', store: "Sam's Club")
food_item138 = FoodItem.create!(name: 'Palillos dientes', store: "Sam's Club")
food_item139 = FoodItem.create!(name: 'Palillos cafe', store: "Sam's Club")
food_item140 = FoodItem.create!(name: 'Papel toalla POM', store: "Sam's Club")
food_item141 = FoodItem.create!(name: 'Picnic Pack', store: "Sam's Club")
food_item142 = FoodItem.create!(name: 'Cuchillo', store: "Sam's Club")
food_item143 = FoodItem.create!(name: 'Tenedores', store: "Sam's Club")
food_item144 = FoodItem.create!(name: 'Cucharas', store: "Sam's Club")
food_item145 = FoodItem.create!(name: 'Platos desechables', store: "Sam's Club")
food_item146 = FoodItem.create!(name: 'Clorox verde', store: "Sam's Club")
food_item147 = FoodItem.create!(name: 'Lysol', store: "Sam's Club")
food_item148 = FoodItem.create!(name: 'Toallas azules', store: "Sam's Club")
food_item149 = FoodItem.create!(name: 'Splenda', store: "Sam's Club")
food_item150 = FoodItem.create!(name: 'Bolsa Gabacha', store: "Sam's Club")
food_item151 = FoodItem.create!(name: 'Salsa A1', store: "Sam's Club")
food_item152 = FoodItem.create!(name: 'Tabasco', store: "Sam's Club")
food_item153 = FoodItem.create!(name: 'Salsa verde picosa', store: "Sam's Club")
food_item154 = FoodItem.create!(name: 'Agua en botella', store: "Sam's Club")
food_item155 = FoodItem.create!(name: 'Te lipton', store: "Sam's Club")
food_item156 = FoodItem.create!(name: 'Focos', store: "Sam's Club")
food_item157 = FoodItem.create!(name: 'coca-cola', store: "Sam's Club")
food_item158 = FoodItem.create!(name: 'coca dieta', store: "Sam's Club")
food_item159 = FoodItem.create!(name: 'Sprite/soda', store: "Sam's Club")
food_item160 = FoodItem.create!(name: 'Cafe', store: "Sam's Club")
food_item161 = FoodItem.create!(name: 'Garbanzo', store: "Sam's Club")
food_item162 = FoodItem.create!(name: 'Tuti frutti', store: "Sam's Club")
food_item163 = FoodItem.create!(name: 'Steel Staninless', store: "Sam's Club")
food_item164 = FoodItem.create!(name: 'Filtros para cafe', store: "Sam's Club")
food_item165 = FoodItem.create!(name: 'Aceite Mazola', store: "Sam's Club")
food_item166 = FoodItem.create!(name: 'Fabuloso', store: "Sam's Club")
food_item167 = FoodItem.create!(name: 'Cuchillos metal', store: "Sam's Club")
food_item168 = FoodItem.create!(name: 'Cucharas metal', store: "Sam's Club")
food_item169 = FoodItem.create!(name: 'Tenedores metal', store: "Sam's Club")
food_item170 = FoodItem.create!(name: 'Garlit sal/pescado', store: "Sam's Club")
food_item171 = FoodItem.create!(name: 'Baking powder', store: "Sam's Club")
food_item172 = FoodItem.create!(name: 'Elote/Atol', store: "Sam's Club")
food_item173 = FoodItem.create!(name: 'Harina para Pan', store: "Sam's Club")
food_item174 = FoodItem.create!(name: 'Queso parmesano', store: "Sam's Club")
food_item175 = FoodItem.create!(name: 'Sour Cream', store: "Sam's Club")
food_item176 = FoodItem.create!(name: 'Pasas', store: "Sam's Club")
food_item177 = FoodItem.create!(name: 'PAM', store: "Sam's Club")
food_item178 = FoodItem.create!(name: 'Manteca Crisco', store: "Sam's Club")
food_item179 = FoodItem.create!(name: 'Toallas blancas', store: "Sam's Club")
food_item180 = FoodItem.create!(name: 'Papel / hornear', store: "Sam's Club")
food_item181 = FoodItem.create!(name: 'Latas alum Gran', store: "Sam's Club")
food_item182 = FoodItem.create!(name: 'Latas alum Pequ', store: "Sam's Club")
food_item183 = FoodItem.create!(name: 'Alumin Perforado', store: "Sam's Club")
food_item184 = FoodItem.create!(name: 'Jabon platos', store: "Sam's Club")
food_item185 = FoodItem.create!(name: 'Clorox', store: "Sam's Club")
food_item186 = FoodItem.create!(name: 'Windex', store: "Sam's Club")
food_item187 = FoodItem.create!(name: 'Olor para baños', store: "Sam's Club")
food_item188 = FoodItem.create!(name: 'Jugo de Limon', store: "Sam's Club")
food_item189 = FoodItem.create!(name: 'Mostaza', store: "Sam's Club")
food_item190 = FoodItem.create!(name: 'Mayonesa', store: "Sam's Club")
food_item191 = FoodItem.create!(name: 'Desengrasador', store: "Sam's Club")
food_item192 = FoodItem.create!(name: 'Trapeador', store: "Sam's Club")
food_item193 = FoodItem.create!(name: 'Palo trapeador', store: "Sam's Club")
food_item194 = FoodItem.create!(name: 'Mascon verde', store: "Sam's Club")
food_item195 = FoodItem.create!(name: 'Mascon alambre', store: "Sam's Club")
food_item196 = FoodItem.create!(name: 'Plastico comida', store: "Sam's Club")
food_item197 = FoodItem.create!(name: 'Vasos licuados', store: "Sam's Club")
food_item198 = FoodItem.create!(name: 'Tapa vasos licuad', store: "Sam's Club")
food_item199 = FoodItem.create!(name: 'Garbanzos', store: "Sam's Club")
food_item200 = FoodItem.create!(name: 'Piña para pasteles', store: "Sam's Club")

# Restaurant Depot
food_item201 = FoodItem.create!(name: 'Uva/soda', store: 'Restaurant Depot')
food_item202 = FoodItem.create!(name: 'Naranja/soda', store: 'Restaurant Depot')
food_item203 = FoodItem.create!(name: 'Azucar paquetitos', store: 'Restaurant Depot')
food_item204 = FoodItem.create!(name: 'Sal paquetitos', store: 'Restaurant Depot')
food_item205 = FoodItem.create!(name: 'Arroz', store: 'Restaurant Depot')
food_item206 = FoodItem.create!(name: 'Harina de Arroz', store: 'Restaurant Depot')
food_item207 = FoodItem.create!(name: 'Jugo naranja', store: 'Restaurant Depot')
food_item208 = FoodItem.create!(name: 'Jugo manzana', store: 'Restaurant Depot')
food_item209 = FoodItem.create!(name: 'Soda naranja', store: 'Restaurant Depot')
food_item210 = FoodItem.create!(name: 'Leche galon', store: 'Restaurant Depot')
food_item211 = FoodItem.create!(name: 'Carne Molida', store: 'Restaurant Depot')
food_item212 = FoodItem.create!(name: 'Carne deshilada', store: 'Restaurant Depot')
food_item213 = FoodItem.create!(name: 'Stiker para la fecha', store: 'Restaurant Depot')
food_item214 = FoodItem.create!(name: 'Tinta impresora coci', store: 'Restaurant Depot')
food_item215 = FoodItem.create!(name: 'Papel impre cocina', store: 'Restaurant Depot')
food_item216 = FoodItem.create!(name: 'Papel impresora caja', store: 'Restaurant Depot')
food_item217 = FoodItem.create!(name: 'Papel impresora tarje', store: 'Restaurant Depot')
food_item218 = FoodItem.create!(name: 'Alfombras de hule', store: 'Restaurant Depot')
food_item219 = FoodItem.create!(name: 'Papas para freir', store: 'Restaurant Depot')
food_item220 = FoodItem.create!(name: 'Fresa congelada', store: 'Restaurant Depot')
food_item221 = FoodItem.create!(name: 'Chisperos', store: 'Restaurant Depot')
food_item222 = FoodItem.create!(name: 'Guantes para hornear', store: 'Restaurant Depot')
food_item223 = FoodItem.create!(name: 'Stickers rojos', store: 'Restaurant Depot')
food_item224 = FoodItem.create!(name: 'Caja clarita para Flan', store: 'Restaurant Depot')
food_item225 = FoodItem.create!(name: 'Vasos 20 onzas', store: 'Restaurant Depot')
food_item226 = FoodItem.create!(name: 'Tapadera vaso 20 on', store: 'Restaurant Depot')
food_item227 = FoodItem.create!(name: 'Aceite de Freidora', store: 'Restaurant Depot')
food_item228 = FoodItem.create!(name: 'Horchata en pasta', store: 'Restaurant Depot')
food_item229 = FoodItem.create!(name: 'Esencia de vainilla', store: 'Restaurant Depot')
food_item230 = FoodItem.create!(name: 'Esencia de Piña', store: 'Restaurant Depot')
food_item231 = FoodItem.create!(name: 'Esencia de Fresa', store: 'Restaurant Depot')

# Central Kitchen
food_item234 = FoodItem.create!(name: 'Queso', store: 'Central Kitchen')
food_item235 = FoodItem.create!(name: 'Chicharron', store: 'Central Kitchen')
food_item236 = FoodItem.create!(name: 'Carne Preparada', store: 'Central Kitchen')
food_item237 = FoodItem.create!(name: 'Masa de Nuegado', store: 'Central Kitchen')
food_item238 = FoodItem.create!(name: 'Frijoles', store: 'Central Kitchen')
food_item239 = FoodItem.create!(name: 'Curtido Pupusa', store: 'Central Kitchen')
food_item240 = FoodItem.create!(name: 'Mariscadas', store: 'Central Kitchen')
food_item241 = FoodItem.create!(name: 'Polvo para Mariscadas', store: 'Central Kitchen')